# Creating a deployment file for dev environment
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: i27-eureka-dev
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: i27-eureka-dev
  template:
    imagePullSecrets: 
      - name: docker-secret  #same name you created "docker-registry secret" under dev namespace
    metadata:
      labels:
        app: i27-eureka-dev
    spec:
      containers:
        - name: i27-eureka-dev
          image: DIT   # "DIT" your own name, which will later replacez with shared libraries
---
# Service 
apiVersion: v1
kind: Service
metadata: 
  name: i27-eureka-dev-svc
spec:  
  selector: 
    app: i27-eureka-dev #this name matches with the above matadata->labelname, otherwise it won't create the endpoint
  ports:
    - protocol: TCP
      port: 80    # This is service port, any port you need
      targetPort: 8761  # Same as your application port
  type: ClusterIP

---
# creating a ingress for your domain (domainname= cart.rakesh.dev.com)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-dev-ingress
  namespace: default
spec:
  rules:
    - host: cart.rakesh.dev.com  # ip's changing so we created domain name and using that domain name here and paste this name for application.yaml
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: i27-eureka-dev-svc  # Correct service name
                port:
                  number: 80   